title: John Jewell # your name (or website title) here
logo: "/images/photo cv v3.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Bonjour et bienvenue sur mon portfolio ! 
  <br><br>
  Bio: ðŸ‘‹ Ã‰tudiant en Master Marketing & Data Analytics Ã  lâ€™UniversitÃ© de Montpellier. PassionnÃ© par lâ€™analyse de donnÃ©es, la stratÃ©gie marketing et les solutions data-driven. Toujours curieux d'apprendre et dâ€™explorer de nouveaux outils technologiques.
  <a href="https://www.linkedin.com/in/john-jewell-73b1601b9/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-DNY4XTB0MR # your Google Analytics tracking ID here
